#include <idt.h>
#include <apic.h>
#include <cpu.h>
#include <serial.h>
#include <timer.h>
#include <panic.h>
#include <sched.h>
#include <atomic.h>
#include <ps2_kbd.h>

static struct idt_ptr idtr;
static struct idt_entry idt[256];

static int idt_initialized = 0;

/* Generated by idt_stubs.asm */
extern uint64_t isr_stub_table[];

void exception_handler(interrupt_frame_t* frame) {
    uint64_t cr2;
    __asm__ volatile("mov %%cr2, %0" : "=r"(cr2));

    kprintf("\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n");
    kprintf("!!!          CPU EXCEPTION         !!!\n");
    kprintf("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n");
    kprintf("Vector: %p | Error Code: %p\n", 
            frame->vector_number, frame->error_code);
            
    kprintf("RIP:    %p\n", frame->rip);
    kprintf("CR2 (Fault Address): %p\n", cr2);
    
    kprintf("RAX:    %p | RBX: %p\n", 
            frame->rax, frame->rbx);

    kprintf("Stack at: %p\n", frame->rsp);
    kprintf("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n");
    
    panic("Unhandled CPU Exception");  // !!! WILL BE CHANGED !!!
}

void idt_set_descriptor(uint8_t vector, void* isr, uint8_t flags) {
    uintptr_t addr = (uintptr_t)isr;
    idt[vector].isr_low    = addr & 0xFFFF;
    idt[vector].kernel_cs  = 0x08; // Kernel Code Segment
    idt[vector].ist        = 0;
    idt[vector].attributes = flags;
    idt[vector].isr_mid    = (addr >> 16) & 0xFFFF;
    idt[vector].isr_high   = (addr >> 32) & 0xFFFFFFFF;
    idt[vector].reserved   = 0;
}

uint64_t interrupt_dispatch(interrupt_frame_t* frame) {
    uint64_t next_rsp = (uint64_t)frame;

    if (frame->vector_number < 32) {
        exception_handler(frame);
    } else if (frame->vector_number == 32) {
        if (get_cpu()->cpu_id == 0)
        system_uptime_ms += 5; // BSP only
        
        sched_update_sleepers();
        lapic_send_eoi();
        
        next_rsp = schedule(frame);
    } else if (frame->vector_number == 33) {
        ps2_keyboard_handler();
        lapic_send_eoi();
    } else if (frame->vector_number == IPI_VECTOR_TEST) {
        // Flush TLB
        cpu_flush_tlb();
        lapic_send_eoi();
    } else if (frame->vector_number == IPI_VECTOR_HALT) {
        __asm__ volatile("cli");
        for(;;) __asm__ volatile("hlt");
    } else {
        lapic_send_eoi();
    }

    return next_rsp;
}

/* Initialization of IDT */
void idt_init() {
    if (!idt_initialized) {
        for (int i = 0; i < 256; i++) {
            idt_set_descriptor(i, (void*)isr_stub_table[i], 0x8E);
        }
        idtr.base = (uintptr_t)&idt[0];
        idtr.limit = (uint16_t)sizeof(idt) - 1;
        idt_initialized = 1;
    }

    __asm__ volatile ("lidt %0" : : "m"(idtr));
}
